### ISSUE TITLE
Incompatibility with Mac keyboard layout

### ISSUE THREAD

**Issue by alexschomb** [NodeBB-Community/nodebb-plugin-shortcuts#6]
The shortcut `ALT+L` that is currently provided for `actions.composer.list` is identical to that of the `@` symbol on Apple Mac compatible keyboards. As a result `nodebb-plugin-shortcuts` automatically creates a new list item and jumps the cursor to the text ending of the post that is currently written/edited. This can be very annoying and intransparent to forum users.

**Comment by frissdiegurke** [comment]
I've replaced the default binding for list items with `Alt+T` now.
This has the following negative effect though: When the composer is opened all shortcuts for changing to */tags* are overwritten with composer-specific actions (insert list item and focus composer title).

But since german (btw. would've been great to mention in first place) mac layout is fairly popular the compatibility is of cause more important.

Thanks for report.

**Comment by alexschomb** [comment]
Sorry, I wasn't aware of the fact that this shortcut only exists on German Mac keyboards. Now that you say it, I remember. :)

Thank you for the quick solution.
